- name: Deploy usb0 network config
  ansible.builtin.template:
    src: 30-usb0.network.j2
    dest: /etc/systemd/network/30-usb0.network
    owner: root
    group: root
    mode: "0644"
  notify: Reload networkd

- name: Enable systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd.service
    enabled: true
    state: started
