name: flutter_ui
description: Smartcar head-unit UI — Android Auto display powered by Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
